name: Build and Deploy
on:
  push:
    branches: [working-on]  # Trigger when pushing to dev branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build Ren'Py (same as before)
      - name: Build Web Version
        run: |
          wget https://www.renpy.org/dl/8.1.3/renpy-8.1.3-sdk.tar.bz2
          tar -xf renpy-*.tar.bz2
          ./renpy-8.1.3-sdk/renpy.sh ./game/ export --web

      # New: Deploy via Actions (not branch)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./game/web
          # No need for destination_dir - deploys directly
