name: Deploy Ren'Py Game
on:
  push:
    branches: [current-release]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # 1. Proper checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Build Ren'Py
      - name: Build Web Version
        run: |
          wget https://www.renpy.org/dl/8.1.3/renpy-8.1.3-sdk.tar.bz2
          tar -xf renpy-*.tar.bz2
          ./renpy-8.1.3-sdk/renpy.sh ./game/ export --web

      # 3. Deploy
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: game/web

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v3
