name: Proper Fix
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. CORRECT CHECKOUT - Add fetch-depth and token
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fixes shallow clone issues
          token: ${{ secrets.GITHUB_TOKEN }}  # Explicit permissions

      # 2. VERIFY FILES EXIST
      - name: Check Files
        run: |
          echo "Repository contents:"
          ls -R
          [ -f game/script.rpy ] || { echo "ERROR: script.rpy missing"; exit 1; }

      # Rest of your workflow...
