name: Deploy Ren'Py Game
on:
  push:
    branches: [current-release]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # 1. Checkout with proper configuration
      - uses: actions/checkout@v4
        with:
          path: the-question-VN-test
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. Verify repository structure
      - name: Verify Files
        run: |
          cd the-question-VN-test
          echo "Repository contents:"
          ls -R
          [ -f game/script.rpy ] || { echo "::error::script.rpy missing"; exit 1; }

      # 3. Install Ren'Py with verification
      - name: Install Ren'Py
        run: |
          cd the-question-VN-test
          wget https://www.renpy.org/dl/8.1.3/renpy-8.1.3-sdk.tar.bz2
          tar -xf renpy-*.tar.bz2
          chmod +x renpy-8.1.3-sdk/renpy.sh
          echo "Ren'Py version:"
          ./renpy-8.1.3-sdk/renpy.sh --version

      # 4. Build with complete debugging
      - name: Build Web Version
        run: |
          cd the-question-VN-test
          echo "Pre-build contents:"
          ls -la game/
          
          # Clean previous build
          rm -rf game/web || true
          
          # Execute build
          set -x
          ./renpy-8.1.3-sdk/renpy.sh ./game/ export --web
          set +x
          
          echo "Post-build contents:"
          ls -la game/web/
          [ -f game/web/index.html ] || { echo "::error::index.html missing"; exit 1; }

      # 5. Prepare deployment
      - name: Prepare Artifact
        run: |
          cd the-question-VN-test/game/web
          touch .nojekyll
          echo "Files to deploy:"
          ls -la

      # 6. Deploy
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: the-question-VN-test/game/web

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v3
