name: Guaranteed Placeholder
on:
  workflow_dispatch:
  push:
    branches: [current-release]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Create files without Git
      - name: Generate Static Files
        run: |
          mkdir -p public
          cat <<EOF > public/index.html
          <!DOCTYPE html>
          <html>
          <head>
            <title>The Question VN</title>
            <meta http-equiv="refresh" content="5">
            <style>
              body { 
                font-family: Arial, sans-serif;
                background: #f5f5f5;
                text-align: center;
                padding: 50px;
              }
              .spinner {
                margin: 20px auto;
                width: 50px;
                height: 50px;
                border: 5px solid rgba(0,0,0,0.1);
                border-radius: 50%;
                border-top-color: #3498db;
                animation: spin 1s linear infinite;
              }
              @keyframes spin {
                to { transform: rotate(360deg); }
              }
            </style>
          </head>
          <body>
            <div class="spinner"></div>
            <h1>Loading The Question Visual Novel</h1>
            <p>Please wait while we build the game...</p>
          </body>
          </html>
          EOF

      # 2. Deploy via direct upload (no Git)
      - name: Upload to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: public
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
