name: Ensure Live Site
on:
  push:
    branches: [current-release]

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout without LFS
        uses: actions/checkout@v4
        with:
          lfs: false  # Disable Git LFS if not needed
          path: the-question-VN-test  # Explicit path

      - name: Create Minimum Site
        run: |
          mkdir -p the-question-VN-test/game/web
          cat <<EOF > the-question-VN-test/game/web/index.html
          <!DOCTYPE html>
          <html>
            <head>
              <title>Game Loading</title>
              <meta http-equiv="refresh" content="5">
            </head>
            <body>
              <h1>🛠️ Game is building...</h1>
              <p>Auto-refreshing in 5 seconds</p>
            </body>
          </html>
          EOF

      - name: Deploy Placeholder
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: the-question-VN-test/game/web
          keep_files: false
