name: Guaranteed Deployment
on:
  workflow_dispatch:
  push:
    branches: [current-release]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Create files directly (no checkout)
      - name: Generate Static Files
        run: |
          mkdir -p ~/game-build
          cat <<'EOF' > ~/game-build/index.html
          <!DOCTYPE html>
          <html>
          <head>
            <title>The Question VN</title>
            <script>
              let retries = 0;
              function checkGame() {
                fetch('game.html')
                  .then(r => r.status === 200 ? location.assign('game.html') : retry())
                  .catch(retry);
              }
              function retry() {
                if (retries++ < 10) setTimeout(checkGame, 3000);
              }
              checkGame();
            </script>
          </head>
          <body>
            <h1>🔄 Loading Game Assets...</h1>
            <p>This may take a few minutes on first load</p>
          </body>
          </html>
          EOF

      # 2. Direct upload via GitHub API
      - name: Deploy via HTTP
        uses: skx/github-action-publish-dir@v2
        with:
          dir: ~/game-build
          branch: gh-pages
          verbose: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
