name: Deploy Ren'Py Game
on:
  push:
    branches: [current-release]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout
      - uses: actions/checkout@v4
        with:
          path: the-question-VN-test
          fetch-depth: 0

      # 2. Install Ren'Py 
      - name: Install Ren'Py
        run: |
          cd the-question-VN-test
          wget https://www.renpy.org/dl/8.1.3/renpy-8.1.3-sdk.tar.bz2
          tar -xf renpy-*.tar.bz2
          chmod +x renpy-8.1.3-sdk/renpy.sh

      # 3. Build Web Version
      - name: Build Game
        run: |
          cd the-question-VN-test
          ./renpy-8.1.3-sdk/renpy.sh ./game/ export --web
          echo "Built files:"
          ls -la game/web/

      # 4. Deploy (CRITICAL FIX: Correct action names)
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v2  # Note: @v2 not @v3

      - name: Deploy
        uses: actions/deploy-pages@v3
