name: Deploy Ren'Py Game
on:
  push:
    branches: [current-release]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # 1. Checkout with path specification
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: the-question-VN-test  # Critical for your structure

      # 2. Build with verification
      - name: Build Web Version
        run: |
          cd the-question-VN-test
          wget https://www.renpy.org/dl/8.1.3/renpy-8.1.3-sdk.tar.bz2
          tar -xf renpy-*.tar.bz2
          chmod +x renpy-8.1.3-sdk/renpy.sh
          
          # Build with verification
          if ! ./renpy-8.1.3-sdk/renpy.sh ./game/ export --web; then
            echo "::error::Ren'Py build failed"
            exit 1
          fi
          
          # Verify critical files
          [ -f game/web/index.html ] || { echo "::error::index.html missing"; exit 1; }
          echo "Build successful! Files:"
          ls -la game/web/

      # 3. Deploy with .nojekyll
      - name: Prepare Deployment
        run: |
          cd the-question-VN-test/game/web
          touch .nojekyll  # Bypass Jekyll processing
          echo "Deploying from: $(pwd)"
          ls -la

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: the-question-VN-test/game/web
          retention-days: 1

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v3
