name: Ensure Live Site
on:
  push:
    branches: [current-release]

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Minimum Site
        run: |
          mkdir -p the-question-VN-test/game/web
          echo "<!DOCTYPE html>
          <html>
            <body>
              <h1>Game is building...</h1>
              <p>Next refresh will show the game</p>
            </body>
          </html>" > the-question-VN-test/game/web/index.html

      - name: Deploy Placeholder
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./the-question-VN-test/game/web
