name: Build and Deploy Stable Release
on:
  push:
    branches: [current-release]  # Only run on pushes to `current-release`

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repo
      - uses: actions/checkout@v4

      # 2. Download Ren'Py SDK
      - name: Set up Ren'Py
        run: |
          wget https://www.renpy.org/dl/8.1.3/renpy-8.1.3-sdk.tar.bz2
          tar -xf renpy-*.tar.bz2

      # 3. Build the web version
      - name: Build Ren'Py Web
        run: |
          ./renpy-8.1.3-sdk/renpy.sh ./game/ export --web

      # 4. Deploy to GitHub Pages (only for stable branch)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./game/web
