name: Base Deployment
on:
  push:
    branches: [current-release]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create placeholder
        run: |
          mkdir -p web
          echo "<h1>Coming Soon</h1>" > web/index.html

      - uses: actions/upload-pages-artifact@v2
        with:
          path: web

      - uses: actions/deploy-pages@v3
