name: Deploy Ren'Py Game
on:
  push:
    branches: [current-release]
  workflow_dispatch:
    branches: [current-release]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # 1. Checkout
      - uses: actions/checkout@v4
        with:
          path: the-question-VN-test
          ref: current-release
          fetch-depth: 0

      # 2. Install Ren'Py
      - name: Setup Ren'Py
        run: |
          cd the-question-VN-test
          wget https://www.renpy.org/dl/8.1.3/renpy-8.1.3-sdk.tar.bz2
          tar -xf renpy-*.tar.bz2
          chmod +x renpy-8.1.3-sdk/renpy.sh

      # 3. Build
      - name: Build Web Export
        run: |
          cd the-question-VN-test
          ./renpy-8.1.3-sdk/renpy.sh ./game/ export --web
          [ -f game/web/index.html ] || { echo "::error::Build failed - no index.html"; exit 1; }

      # 4. Deploy (ONLY uses pages-specific actions)
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: the-question-VN-test/game/web

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v3
